import dotenv from "dotenv";
dotenv.config();

export const {
	TOKEN,
	CLIENT_ID,
	GUILD_ID,
	PROD_CHANNEL_ID,
	DEV_CHANNEL_ID,
	ETHEREUM_HOST,
	ETHEREUM_ROLLUP_ADDRESS,
	ETHEREUM_ADMIN_ADDRESS,
	ETHEREUM_CHAIN_ID,
	ETHEREUM_MNEMONIC,
	ETHEREUM_PRIVATE_KEY,
	ETHEREUM_VALUE,
	BOT_TOKEN,
	BOT_CLIENT_ID,
	ENVIRONMENT,
} = process.env as {
	TOKEN: string;
	CLIENT_ID: string;
	GUILD_ID: string;
	PROD_CHANNEL_ID: string;
	DEV_CHANNEL_ID: string;
	ETHEREUM_HOST: string;
	ETHEREUM_ROLLUP_ADDRESS: string;
	ETHEREUM_ADMIN_ADDRESS: string;
	ETHEREUM_CHAIN_ID: string;
	ETHEREUM_MNEMONIC: string;
	ETHEREUM_PRIVATE_KEY: string;
	ETHEREUM_VALUE: string;
	BOT_TOKEN: string;
	PRODUCTION_CHANNEL_ID: string;
	BOT_CLIENT_ID: string;
	ENVIRONMENT: string;
};
