services:
    dynamodb-local:
        container_name: dynamodb-local
        ports:
            - 8000:8000
        image: amazon/dynamodb-local:latest
        env_file:
            - .env
        command: -jar DynamoDBLocal.jar -sharedDb

    anvil:
      image: ghcr.io/foundry-rs/foundry
      container_name: anvil
      working_dir: /anvil
      environment:
        ANVIL_IP_ADDR: "0.0.0.0"
      ports:
        - "8545:8545"
      command: anvil